
import { ReactNode } from 'react';

export enum View {
  SPLASH = 'SPLASH',
  ONBOARDING = 'ONBOARDING',
  AUTH = 'AUTH',
  DASHBOARD = 'DASHBOARD',
  ATTENDANCE = 'ATTENDANCE',
  HOMEWORK = 'HOMEWORK',
  TIMETABLE = 'TIMETABLE',
  EXAM_SCHEDULE = 'EXAM_SCHEDULE',
  RESULTS = 'RESULTS',
  FEES = 'FEES',
  NOTICES = 'NOTICES',
  GALLERY = 'GALLERY',
  LOCATION = 'LOCATION',
  CHAT = 'CHAT',
  PROFILE = 'PROFILE',
  LEAVE = 'LEAVE',
  MATERIALS = 'MATERIALS',
  CONTACT = 'CONTACT',
  
  // Super Admin Views
  SUPER_DASHBOARD = 'SUPER_DASHBOARD',
  SUPER_SETTINGS = 'SUPER_SETTINGS',
  SUPER_ADD_ADMIN = 'SUPER_ADD_ADMIN',
  SUPER_ADD_TEACHER = 'SUPER_ADD_TEACHER',
  SUPER_CLASSES = 'SUPER_CLASSES',
  SUPER_APPROVE = 'SUPER_APPROVE',
  SUPER_ANALYTICS = 'SUPER_ANALYTICS',
  SUPER_NOTIFICATIONS = 'SUPER_NOTIFICATIONS',
  SUPER_LOGS = 'SUPER_LOGS',

  // Admin (Principal) Views
  ADMIN_DASHBOARD = 'ADMIN_DASHBOARD',
  ADMIN_ATTENDANCE = 'ADMIN_ATTENDANCE',
  ADMIN_LEAVES = 'ADMIN_LEAVES',
  ADMIN_TEACHERS = 'ADMIN_TEACHERS',
  ADMIN_STUDENTS = 'ADMIN_STUDENTS',
  ADMIN_TIMETABLE = 'ADMIN_TIMETABLE',
  ADMIN_RESULTS = 'ADMIN_RESULTS',
  ADMIN_FEES = 'ADMIN_FEES',
  ADMIN_NOTICES = 'ADMIN_NOTICES',
  ADMIN_GALLERY = 'ADMIN_GALLERY',
  ADMIN_CHAT = 'ADMIN_CHAT',
  ADMIN_PROFILE = 'ADMIN_PROFILE',

  // Teacher Views
  TEACHER_DASHBOARD = 'TEACHER_DASHBOARD',
  TEACHER_ATTENDANCE = 'TEACHER_ATTENDANCE',
  TEACHER_HOMEWORK = 'TEACHER_HOMEWORK',
  TEACHER_NOTICES = 'TEACHER_NOTICES',
  TEACHER_STUDENTS = 'TEACHER_STUDENTS',
  TEACHER_PROFILE = 'TEACHER_PROFILE',

  // Parent Views
  PARENT_DASHBOARD = 'PARENT_DASHBOARD',
  PARENT_ATTENDANCE = 'PARENT_ATTENDANCE',
  PARENT_HOMEWORK = 'PARENT_HOMEWORK',
  PARENT_TIMETABLE = 'PARENT_TIMETABLE',
  PARENT_EXAM_SCHEDULE = 'PARENT_EXAM_SCHEDULE',
  PARENT_RESULTS = 'PARENT_RESULTS',
  PARENT_FEES = 'PARENT_FEES',
  PARENT_NOTICES = 'PARENT_NOTICES',
  PARENT_GALLERY = 'PARENT_GALLERY',
  PARENT_BUS = 'PARENT_BUS',
  PARENT_CHAT = 'PARENT_CHAT',
  PARENT_PROFILE = 'PARENT_PROFILE',
}

export interface NavItem {
  id: View;
  label: string;
  icon: any;
}

export interface Student {
  name: string;
  grade: string;
  section: string;
  rollNo: string;
  avatar: string;
  stats: {
    attendance: number;
    avgGrade: string;
    assignments: number;
  }
}

export interface ChatMessage {
  id: string;
  text: string;
  sender: 'user' | 'other' | 'ai';
  timestamp: Date;
}
